s1=input("enter the first name")
s2=input("enter the last name")
a=int(input("enter the age"))
b=int(input("enter the salary"))

print("name is "+ s1+" "+s2)
print(s1[3])
print(s1[-3])
print(bin(a),bin(b))
print(type(s1))
print(type(a))
print(ord(s1[0]))
print(ord(s2[-1]))
print(s1[:])
print(s1[2:])
print(s1[:5])
print(s1[0:6:2])
print(len(s1))
print(s1.count("P"))
print(s1.find("t"))
